# Generated by Django 6.1 on 2026-08-17 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Toilet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='화장실명')),
                ('address', models.CharField(max_length=255, verbose_name='주소')),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('longitude', models.FloatField(verbose_name='경도')),
                ('opening_hours', models.CharField(default='상시 개방', max_length=120, verbose_name='운영시간')),
                ('is_open_24h', models.BooleanField(default=False, verbose_name='24시간')),
                ('accessible', models.BooleanField(default=False, verbose_name='장애인 시설')),
                ('provider', models.CharField(default='샘플 데이터', max_length=80, verbose_name='데이터 제공처')),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SafetyContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cctv_distance_m', models.PositiveIntegerField(blank=True, null=True, verbose_name='최근접 CCTV 거리')),
                ('is_protected_zone', models.BooleanField(default=False, verbose_name='보호구역')),
                ('enforcement_risk', models.PositiveSmallIntegerField(default=20, verbose_name='단속 위험도')),
                ('toilet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety', to='services.toilet')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='주차장명')),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('longitude', models.FloatField(verbose_name='경도')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='주차면')),
                ('is_public', models.BooleanField(default=True, verbose_name='공영')),
                ('fee_type', models.CharField(default='유료', max_length=40, verbose_name='요금')),
                ('toilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_lots', to='services.toilet')),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('OPEN', '정상 이용 가능'), ('CLOSED', '문이 닫혀 있음'), ('PARKING_AVAILABLE', '주차 여유 있음'), ('PARKING_DIFFICULT', '주차 어려움'), ('ENFORCEMENT_SEEN', '단속 차량 목격'), ('CLEAN', '깨끗함'), ('DIRTY', '청결 불량')], max_length=30, verbose_name='제보 유형')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='한 줄 제보')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('toilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='services.toilet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
