# Generated by Django 6.1 on 2026-08-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='access_info',
            field=models.CharField(blank=True, max_length=160, verbose_name='출입 안내'),
        ),
        migrations.AddField(
            model_name='toilet',
            name='facility_type',
            field=models.CharField(choices=[('PUBLIC', '공중화장실'), ('OPEN', '개방화장실'), ('REST_AREA', '택시쉼터 화장실')], default='PUBLIC', max_length=20, verbose_name='시설 유형'),
        ),
        migrations.AddField(
            model_name='toilet',
            name='is_officially_designated',
            field=models.BooleanField(default=True, verbose_name='공식 지정'),
        ),
    ]
